---
- name: Download Sury repository GPG key
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /usr/share/keyrings/deb.sury.org-php.gpg

- name: Add Sury repository for PHP
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    filename: php
    state: present
    update_cache: true

- name: Install Apache, PHP, PostgreSQL and cron
  apt:
    name: apache2, php, postgresql, cron
    state: present

- name: Install Nextcloud dependencies
  apt:
    name:
      - acl
      - php-apcu
      - php-bcmath
      - php-bz2
      - php-curl
      - php-gd
      - php-gmp
      - php-imagick
      - php-intl
      - php-mbstring
      - php-pgsql
      - php-smbclient
      - php-xml
      - php-zip
      - libmagickcore-6.q16-6-extra
      - python3-psycopg2  # Needed for the postgresql Ansible module
    state: present
